services:
  - type: web
    name: Ray-MD
    env: node
    plan: free
    buildCommand: npm install 
    startCommand: npm start   
    envVars:
      - key: SESSION-ID
        sync: false
      - key: OWNER
        sync: false
      - key: OWNER-NUMBER
        sync: false
      - key: PREFIX
        sync: false
